# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

ARG PYTHON_VERSION=3.14
FROM python:${PYTHON_VERSION}-alpine3.23 AS base

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1


WORKDIR /todo_app/backend

# # Create a non-privileged user that the app will run under.
# # See https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user
# ARG UID=10001
# RUN adduser \
# --disabled-password \
# --gecos "" \
# --home "/nonexistent" \
# --shell "/sbin/nologin" \
# --no-create-home \
# --uid "${UID}" \
# appuser

RUN apk add --no-cache postgresql-dev gcc musl-dev vim

# Skip curl/sh and just copy the binary directly
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
    
# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.cache/pip to speed up subsequent builds.
# Leverage a bind mount to requirements.txt to avoid having to copy them into
# into this layer.
COPY pyproject.toml uv.lock .python-version /todo_app/backend/

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

# Copy the source code into the container.
COPY . .

# Final sync to install the app itself
RUN uv sync --frozen --no-dev

# # Make non-privileged user owner of app directory
# RUN chown -R appuser:appuser ../backend

# # Switch to the non-privileged user to run the application.
# USER appuser

# Set the virtualenv at the front of the PATH
ENV PATH="/backend/.venv/bin:$PATH"