[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "../README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.129.0",
    "psycopg2-binary>=2.9.11",
    "pytest>=9.0.3",
]

# [tool.ruff]
# lint.extend-select = ["PTH"]
# lint.ignore = ["T201"]