# Use 1 worker per core
worker_processes 1;
# Set limit for open file descriptors (should be > worker_connections)
worker_rlimit_nofile 2000;

events {
    worker_connections 2048;
    multi_accept on;
}

http {
    # 1. Define the Rate Limit Zone (Global memory pool)
    # Allows 6 requests per second (10r/s) per unique IP ($binary_remote_addr)
    limit_req_zone $binary_remote_addr zone=api_req_limit:5m rate=10r/s;

    # 2. Connection Limiting Zone (Total open TCP connections)
    # 10MB can track ~160,000 unique IP addresses
    limit_conn_zone $binary_remote_addr zone=api_conn_limit:5m;

    # Optimization for file serving through API
    client_body_buffer_size 128k;
    proxy_buffers 32 4k; # Helps Nginx handle FastAPI responses efficiently

    # Set error code 429 (Too Many Requests) for both limits
    limit_req_status 429;
    limit_conn_status 429;

    # 2. API Gateway & Compression
    gzip on;
    gzip_types text/plain application/json application/javascript text/css; #
    keepalive_timeout 18; # Balance resource use and connection speed


    server { 
        listen 80;  # port on which nginx listens.
        server_name localhost;
        # server_name my-todoapp.com;
        # client_max_body_size  5m;

        # location = / {
        #     return 301 http://my-todoapp.com/;
        # }

        location / {
            # Apply request rate limit (10 req/sec + 10 burst)
            limit_req zone=api_req_limit burst=10 nodelay;

            # Apply connection limit (Max 10 concurrent connections per IP)
            # Most modern browsers use 6-8 connections; 10 is safe for APIs.
            limit_conn api_conn_limit 10;

            proxy_pass http://app_service:8000/;

            # Standard Proxy Headers
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            # Buffering for file serving
            proxy_buffering on;
        }
    }
}