"""added users

Revision ID: 9032acf75f32
Revises: c6cd811f20e1
Create Date: 2026-06-27 19:54:23.328959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9032acf75f32"
down_revision: Union[str, Sequence[str], None] = "c6cd811f20e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=16), nullable=False),
        sa.Column("last_name", sa.String(length=16), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("hashed_password", sa.String(length=256), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###

    # Rename task → tasks (preserves all existing rows)
    op.rename_table("task", "tasks")

    # Drop old indexes — named for 'task', now orphaned after rename
    op.drop_index("ix_task_id", table_name="tasks")
    op.drop_index("ix_task_name", table_name="tasks")

    # Batch mode: SQLite can't ALTER constraints directly.
    # Alembic will create a new table with the full schema,
    # copy all rows, drop the old table, rename the new one.
    with op.batch_alter_table("tasks") as batch_op:
        # nullable=True temporarily — SQLite rejects NOT NULL with no default
        # if existing rows are present. Safe to tighten below.
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_tasks_owner_id_users",
            "users",
            ["owner_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_index("ix_tasks_id", ["id"], unique=False)
        batch_op.create_index("ix_tasks_name", ["name"], unique=False)
        batch_op.create_index("ix_tasks_owner_id", ["owner_id"], unique=False)

    # # Tighten to NOT NULL once column exists.
    # # If you have existing rows, fill owner_id values before this step.
    # with op.batch_alter_table("tasks") as batch_op:
    #     batch_op.alter_column("owner_id", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_index("ix_tasks_owner_id")
        batch_op.drop_index("ix_tasks_name")
        batch_op.drop_index("ix_tasks_id")
        batch_op.drop_constraint("fk_tasks_owner_id_users", type_="foreignkey")
        batch_op.drop_column("owner_id")
        batch_op.create_index("ix_task_name", ["name"], unique=False)
        batch_op.create_index("ix_task_id", ["id"], unique=False)

    op.rename_table("tasks", "task")

    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_id", table_name="users")
    op.drop_table("users")
